version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: chai
    versions:
    - 4.3.3
  - dependency-name: solidity-coverage
    versions:
    - 0.7.14
    - 0.7.15
    - 0.7.16
  - dependency-name: "@openzeppelin/contracts"
    versions:
    - 3.3.0
    - 3.4.0
    - 3.4.1
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: web3-utils
    versions:
    - 1.3.3
    - 1.3.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: eslint-plugin-jsx-a11y
    versions:
    - 6.4.1
  - dependency-name: acorn
    versions:
    - 7.4.1
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: truffle-flattener
    versions:
    - 1.5.0
  - dependency-name: bl
    versions:
    - 1.2.3
  - dependency-name: yargs-parser
    versions:
    - 13.1.2
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: npm-registry-fetch
    versions:
    - 4.0.7
